<?php

/**
 * @file
 * An Islandora viewer for paged content with a TEI datastream.
 */

/**
 * Implements hook_islandora_viewer_info().
 */
function islandora_paged_tei_seadragon_islandora_viewer_info() {
  return array(
    'islandora_paged_tei_seadragon' => array(
      'label' => t('Paged Content TEI OpenSeadragon viewer'),
      'description' => t('Two paned viewer with rendered TEI on one side and
        page images on the other.'),
      'callback' => 'islandora_paged_tei_seadragon_callback',
      'model' => array(
        'islandora:manuscriptCModel',
        'islandora:bookCModel',
        'islandora:newspaperIssueCModel',
      ),
    ),
  );
}

/**
 * Callback function for the viewer.
 *
 * @param array $params
 *   An array of parameters to pass to islandora_paged_tei_seadragon_viewer.
 *
 * @return string
 *   HTML string for the viewer.
 */
function islandora_paged_tei_seadragon_callback(array $params) {
  return theme('islandora_paged_tei_seadragon_viewer', $params);
}

/**
 * Implements hook_theme().
 */
function islandora_paged_tei_seadragon_theme() {
  // Solution packs using this as a viewer need to set these variables.
  return array(
    'islandora_paged_tei_seadragon_viewer' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-paged-tei-seadragon-viewer',
      'variables' => array(
        'object' => NULL,
        'transform_object' => NULL,
        'pages' => array(),
        'nav_left' => '',
        'nav_right' => '',
        'seadragon' => '',
        'dsids_to_render' => array('PDF', 'JP2', 'TIFF'),
        'tei' => FALSE,
        'download_prefix' => '',
      ),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function islandora_paged_tei_seadragon_menu() {
  $item = array();

  $item['islandora/object/%islandora_object/paged_tei_seadragon_tilesource'] = array(
    'title' => 'Paged Seadragon Tilesource Callback',
    'page callback' => '_islandora_paged_tei_seadragon_tilesource_callback',
    'page arguments' => array(2),
    'access callback' => '_islandora_paged_tei_seadragon_tilesource_access_callback',
    'access arguments' => array(2),
    'file' => 'includes/callbacks.inc',
  );

  return $item;
}

/**
 * Access callback; can datastream, so can get a tilesource for it.
 */
function _islandora_paged_tei_seadragon_tilesource_access_callback($object) {
  return islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $object['JP2']);
}
